### ISSUE TITLE
Should the project ignore the DBT_PROFILES_DIR environmental variable?

### ISSUE THREAD

**Issue by leoebfolsom** [dbeatty10/data-diff-demo#6]
Hi Doug, this is awesome. I just got it up and running in 5(!) minutes! Thanks so much for setting it up.

I did run into one hiccup, which I think might have to do with my own lack of understanding of some of the recent changes to how dbt handles profiles.

I initially received this error:

```
% dbt run -s simple_model --target prod
17:53:26  Encountered an error while reading the project:
17:53:26    ERROR: Runtime Error
  Could not find profile named 'diffle_shop'
17:53:27  Encountered an error:
Runtime Error
  Could not run dbt
```

This occurred (I think) because I've saved an environmental variable in my local `~/.zshrc` file that informs dbt of the location of my `profiles.yml` file.

To that effect, the following line exists in my `.zshrc`:

```
export DBT_PROFILES_DIR=~/.dbt
```

I included that line in my `.zshrc` because in (most) other contexts, I don't want dbt to automatically use the `profiles.yml` file in the project itself.

As a workaround to get this project up and running, I copy/pasted the contents of the project's `profiles.yml` into my local `~/.dbt/profiles.yml`. But ideally, I would use the project's `profiles.yml`, because of course now the profile is not source controlled--not to mention, that's a manual step that is not documented/intuitive.

Could something be included in the README's recommended commands so that even a user who had the profile path configured as a `DBT_PROFILES_DIR` environmental variable (like I did) receive the profile from the project's `profiles.yml`? Or is it a bad/outdated practice to set `DBT_PROFILES_DIR` in `.zshrc`?

**Comment by leoebfolsom** [comment]
I did a bit of learning (aka I asked @dlawin):

> there are 3 possible ways to set the profiles dir with this precedence:
--profiles-dir flag > DBT_PROFILES_DIR > “default directory”

so I think the following update to the Setup section would address what I've raised:

> Establish the baseline production table:
> 
> ```
> dbt run -s simple_model --target prod --profiles-dir .
> ```
>
> Simulate a change to the table during development:
> 
> ```
> dbt run -s simple_model --profiles-dir .
> ```

**Comment by dbeatty10** [comment]
> I just got it up and running in 5(!) minutes! Thanks so much for setting it up.

🎉 Love hearing that @leoebfolsom ! Being able to get up and running as fast and easy as possible was the goal, so I'm delighted to hear that.

The work y'all are doing with `data-diff` is really cool, so excited to see people get introduced to it.

Also, thanks for reaching out and letting me know the barrier you ran into.

### Making the instructions as helpful as possible
Funny story: in this recent commit: https://github.com/dbeatty10/data-diff-demo/commit/df32ccdaffc9c249edd6c50a1a5da38bc4c9af2a, I just **un-did** the commands you are proposing. This was an attempt to make the command as short and sweet as possible.

I really prefer commands to be as brief as humanly possible, but it also bums me out when people have to spend time troubleshooting. All things be equal, I think good instructions should "just work, no matter what".

https://github.com/datafold/data-diff/pull/415 won't address it because it will still favor `DBT_PROFILES_DIR` over any `profiles.yml` in the current working directory. (I just updated the description of that PR to be more clear -- thanks for pointing it out!)

### Options
There's a couple options we could take here:
1. Revert https://github.com/dbeatty10/data-diff-demo/commit/df32ccdaffc9c249edd6c50a1a5da38bc4c9af2a so that it "just works" for everyone
    - accepting that the command will be more verbose
2. Leave https://github.com/dbeatty10/data-diff-demo/commit/df32ccdaffc9c249edd6c50a1a5da38bc4c9af2a as-is and add a caveat that users that have `DBT_PROFILES_DIR` set will need to either a) add another connection to their `~/.dbt/profiles.yml` or b) use the `--profiles-dir` flag
    - accepting that there will be more text within the README, and it won't be as simple as copy-paste for some people
    
I'm leaning towards Option 1.
